import { Item, StoreContact } from './types';

export const STORE_CONTACT: StoreContact = {
  name: 'Shree Renuka Book House & Stationery Hub',
  tagline: "Davangere's Trusted Academic, Kannada Sahitya & Premium Stationery Destination",
  address: {
    shopNo: 'Shop 5',
    building: 'Tennis Court Complex',
    street: 'AVK College Road',
    area: 'Prince Jayachamaraja Wodeyar (PJ Extension)',
    city: 'Davangere',
    state: 'Karnataka',
    pincode: '577004',
    fullAddress: 'Shop 5, Tennis Court Complex, AVK College Road, Prince Jayachamaraja Wodeyar (PJ Extension), Davangere, Karnataka 577004',
    landmark: 'Opposite/Adjacent to AVK College for Women & Tennis Court Complex',
  },
  phoneNumbers: {
    primary: '+91 98807 44487',
    secondary: '+91 86602 80677',
    formattedPrimary: '+919880744487',
    formattedSecondary: '+918660280677',
  },
  email: 'contact@shreerenukabooks.com',
  timings: {
    weekdays: '9:00 AM – 9:30 PM (Mon – Sat)',
    sunday: '9:30 AM – 8:30 PM (Sunday)',
    isOpenToday: true,
  },
  deliveryInfo: {
    davangereCoverage: 'Same-day home delivery across all Davangere areas including PJ Extension, MCC A & B Block, Vidyanagar, KB Extension, Nituvalli, Shamnur Road, and Anjaneya Badavane.',
    outstationDelivery: 'Fast parcel/courier dispatch across all taluks of Davangere (Harihar, Channagiri, Honnali, Jagalur, Harapanahalli) and across Karnataka.',
    orderCallNotice: 'To order or book a delivery, please call +91 98807 44487 or +91 86602 80677 with your book list or stationery requirements. We will pack and dispatch your order promptly!',
  },
  googleMapsUrl: 'https://maps.google.com/?q=AVK+College+Road+PJ+Extension+Davangere+Karnataka+577004',
  googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3863.3850125867493!2d75.9207863!3d14.4627192!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3bba2574041b3127%3A0xb35a09c256cae758!2sAVK%20College%20Rd%2C%20PJ%20Extension%2C%20Davanagere%2C%20Karnataka%20577004!5e0!3m2!1sen!2sin!4v1700000000000!5m2!1sen!2sin',
};

export const PRESET_IMAGE_CATEGORIES = [
  {
    name: 'Academic & Engineering',
    images: [
      { label: 'Engineering Text', url: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?q=80&w=800&auto=format&fit=crop' },
      { label: 'Science / Medical', url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop' },
      { label: 'Mathematics Book', url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=800&auto=format&fit=crop' },
    ],
  },
  {
    name: 'Kannada Sahitya & Novels',
    images: [
      { label: 'Classic Vintage Book', url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop' },
      { label: 'Poetry & Literature', url: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?q=80&w=800&auto=format&fit=crop' },
      { label: 'Modern Novel', url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=800&auto=format&fit=crop' },
    ],
  },
  {
    name: 'Stationery & Supplies',
    images: [
      { label: 'Notebooks Stack', url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=800&auto=format&fit=crop' },
      { label: 'Luxury Pens & Desk', url: 'https://images.unsplash.com/photo-1585336261026-41ff95874251?q=80&w=800&auto=format&fit=crop' },
      { label: 'Drafting & Geometry', url: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?q=80&w=800&auto=format&fit=crop' },
      { label: 'Art & Sketch Kits', url: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop' },
    ],
  },
  {
    name: 'Competitive Exam Prep',
    images: [
      { label: 'Study & Notes Desk', url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800&auto=format&fit=crop' },
      { label: 'Exam Handbook Stack', url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?q=80&w=800&auto=format&fit=crop' },
    ],
  },
];

export const INITIAL_ITEMS: Item[] = [
  // NEW ARRIVALS (Books)
  {
    id: 'item-1',
    title: 'Karvalo (ಕಾರ್ವಾಲೊ) - Special Edition',
    type: 'book',
    category: 'Kannada Literature',
    authorOrBrand: 'Poornachandra Tejaswi',
    price: 180,
    originalPrice: 220,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=800&auto=format&fit=crop',
    description: 'The timeless classic scientific and philosophical adventure novel set in the Western Ghats. Must-read Kannada literature for college students and literary enthusiasts.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['Kannada Sahitya', 'Bestseller', 'Tejaswi', 'Davangere Readers Choice'],
    editionOrSpec: '2026 Deluxe Reprint',
    language: 'Kannada',
    createdAt: '2026-08-20T10:00:00.000Z',
  },
  {
    id: 'item-2',
    title: 'Karnataka KPSC FDA & SDA Complete Guide 2026',
    type: 'book',
    category: 'Competitive Exams',
    authorOrBrand: 'Spardha Chaitra Publications',
    price: 450,
    originalPrice: 550,
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800&auto=format&fit=crop',
    description: 'Updated comprehensive guidebook for Karnataka State FDA, SDA, and Group C recruitment with previous 10 years solved question papers, general knowledge & Kannada grammar.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['KPSC', 'FDA', 'SDA', 'Competitive Exams', 'Karnataka Jobs'],
    editionOrSpec: '2026 Edition',
    language: 'Kannada & English',
    createdAt: '2026-08-22T10:00:00.000Z',
  },
  {
    id: 'item-3',
    title: 'Engineering Mathematics III (VTU / BIET / GMIT Syllabus)',
    type: 'book',
    category: 'Engineering & Medical',
    authorOrBrand: 'Dr. B.S. Grewal',
    price: 620,
    originalPrice: 750,
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=800&auto=format&fit=crop',
    description: 'Prescribed engineering mathematics textbook covering Fourier series, Z-transforms, statistical methods, and numerical methods for 3rd semester engineering students in Davangere colleges.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    tags: ['VTU', 'BIET', 'GMIT', 'Engineering', 'Davangere College'],
    editionOrSpec: '44th Revised Edition',
    language: 'English',
    createdAt: '2026-08-24T10:00:00.000Z',
  },
  {
    id: 'item-4',
    title: 'Davangere University B.Com 4th Sem Corporate Accounting',
    type: 'book',
    category: 'Academic & College',
    authorOrBrand: 'S.P. Jain & K.L. Narang',
    price: 340,
    originalPrice: 400,
    coverImage: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?q=80&w=800&auto=format&fit=crop',
    description: 'Strictly aligned with the latest Davangere University NEP curriculum for B.Com semester 4. Includes valuation of goodwill, shares, amalgamation, and liquidation problem sets.',
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    tags: ['Davangere University', 'AVK College', 'B.Com', 'NEP 2020'],
    editionOrSpec: '2026 NEP Edition',
    language: 'English & Kannada Notes',
    createdAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'item-5',
    title: 'Parva (ಪರ್ವ) - Epic Mahabharata Retold',
    type: 'book',
    category: 'Kannada Literature',
    authorOrBrand: 'S.L. Bhyrappa',
    price: 520,
    originalPrice: 600,
    coverImage: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?q=80&w=800&auto=format&fit=crop',
    description: 'Masterpiece Kannada novel analyzing the epic Mahabharata from a realistic, psychological, and anthropological perspective. A staple for all Davangere book lovers.',
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    isBestSeller: true,
    tags: ['Bhyrappa', 'Kannada Novel', 'Sahitya Akademi'],
    editionOrSpec: 'Deluxe Hardbound',
    language: 'Kannada',
    createdAt: '2026-08-10T10:00:00.000Z',
  },
  {
    id: 'item-6',
    title: '2nd PUC Physics & Chemistry Booster Guide 2026',
    type: 'book',
    category: 'School Textbooks',
    authorOrBrand: 'Expert PU Guidance Panel',
    price: 390,
    originalPrice: 480,
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop',
    description: 'Comprehensive study material for Karnataka State 2nd PUC Board Exam and KCET/NEET preparation. Contains 5 model question papers with step-by-step solutions.',
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    tags: ['PUC', 'Karnataka Board', 'AVK PU College', 'DRM Science'],
    editionOrSpec: '2026 Board Edition',
    language: 'English',
    createdAt: '2026-08-26T10:00:00.000Z',
  },

  // NEW ARRIVALS (Stationery)
  {
    id: 'item-7',
    title: 'Omega Engineering Mini Drafter & Drafting Board Set',
    type: 'stationery',
    category: 'Engineering & Drafting Tools',
    authorOrBrand: 'Omega Technical Instruments',
    price: 550,
    originalPrice: 680,
    coverImage: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?q=80&w=800&auto=format&fit=crop',
    description: 'High-precision unbreakable scale mini drafter with steel clamp and protractor head. Recommended for 1st & 2nd year engineering students of BIET, GMIT, and UBDT.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['Engineering', 'Drawing', 'BIET', 'GMIT', 'Stationery'],
    editionOrSpec: 'Standard College Grade with Canvas Bag',
    createdAt: '2026-08-27T10:00:00.000Z',
  },
  {
    id: 'item-8',
    title: 'Classmate Pulse 6-Subject Spiral Notebook (300 Pages)',
    type: 'stationery',
    category: 'College & School Notebooks',
    authorOrBrand: 'Classmate (ITC)',
    price: 180,
    originalPrice: 210,
    coverImage: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=800&auto=format&fit=crop',
    description: 'Premium ozone-treated elemental chlorine-free paper with movable color dividers and poly cover. Top choice for AVK College, B.Sc, B.Com, and Engineering notes.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['Notebook', 'Classmate', 'College Stationery', 'Davangere Students'],
    editionOrSpec: 'Single Line / Ruled 300 Pages',
    createdAt: '2026-08-25T10:00:00.000Z',
  },
  {
    id: 'item-9',
    title: 'Casio fx-991CW ClassWiz Non-Programmable Scientific Calculator',
    type: 'stationery',
    category: 'Calculators & Electronics',
    authorOrBrand: 'Casio India',
    price: 1395,
    originalPrice: 1595,
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=800&auto=format&fit=crop',
    description: 'Latest 540+ functions natural textbook display scientific calculator approved for VTU, Davangere University, and Engineering exams. Comes with 3-year official warranty.',
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    isBestSeller: true,
    tags: ['Casio', 'Calculator', 'Engineering', 'Exam Approved'],
    editionOrSpec: 'Original with Hologram & 3-Year Warranty',
    createdAt: '2026-08-26T10:00:00.000Z',
  },
  {
    id: 'item-10',
    title: 'Parker Vector Stainless Steel Rollerball & Fountain Pen Set',
    type: 'stationery',
    category: 'Pens & Writing Instruments',
    authorOrBrand: 'Parker Pens',
    price: 680,
    originalPrice: 850,
    coverImage: 'https://images.unsplash.com/photo-1585336261026-41ff95874251?q=80&w=800&auto=format&fit=crop',
    description: 'Elegantly crafted brushed stainless steel pen duo with fine stainless steel nib and Quink ink cartridge. Perfect executive and gifting choice.',
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    tags: ['Parker', 'Luxury Pen', 'Gift Item', 'Office Stationery'],
    editionOrSpec: 'Gift Boxed Edition (Blue Ink)',
    createdAt: '2026-08-15T10:00:00.000Z',
  },
  {
    id: 'item-11',
    title: 'Faber-Castell 24-Shade Professional Artist Watercolor Cake Kit',
    type: 'stationery',
    category: 'Art & Craft Materials',
    authorOrBrand: 'Faber-Castell',
    price: 320,
    originalPrice: 380,
    coverImage: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop',
    description: 'Rich pigment watercolor cakes with water brush pen, mixing palette, and sponge. Ideal for architecture drafting, fine arts students, and hobbyists.',
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    tags: ['Art', 'Watercolor', 'Faber-Castell', 'Architecture'],
    editionOrSpec: '24 Shades + Water Brush',
    createdAt: '2026-08-28T10:00:00.000Z',
  },
  {
    id: 'item-12',
    title: 'Medical Student Dissection Kit (Stainless Steel 14 Tools)',
    type: 'stationery',
    category: 'Medical & Lab Supplies',
    authorOrBrand: 'Surgical Precision Instruments',
    price: 490,
    originalPrice: 650,
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=800&auto=format&fit=crop',
    description: 'Complete 14-piece medical dissection instrument set in zippered leatherette pouch. Essential for JJM Medical College, SSIMS, and B.Sc Zoology practicals.',
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    tags: ['Medical', 'JJMMC', 'SSIMS', 'Lab Kit', 'Davangere Colleges'],
    editionOrSpec: 'Medical Grade Stainless Steel',
    createdAt: '2026-08-12T10:00:00.000Z',
  },
];
